version: "3.4"

services:
  mongoDb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
      - MSSQL_PID=Express
    volumes:
      - "mssql_data:/data/db"

    depends_on:
      - mongoDb

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - mongoDb

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
  mssql_data:
    driver: local

networks:
  default:
    external:
      name: mydockernetwork
